export const STATUS = {
  ACTIVE: 'ACTIVE',
  INACTIVE: 'INACTIVE',
};

export const ENQUIRY_STATUS = {
  NEW: 'NEW',
  CONTACTED: 'CONTACTED',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CLOSED: 'CLOSED',
};

export const ENQUIRY_SOURCE = {
  CONTACT: 'CONTACT',
  PRODUCT: 'PRODUCT',
  SERVICE: 'SERVICE',
  INDUSTRY: 'INDUSTRY',
};
